### ISSUE TITLE
Ensure all metrics within a project are assigned a proper tenant ID

### ISSUE THREAD

**Issue by jmazzitelli** [hawkular/hawkular-openshift-agent#1]
Today, each endpoint can be assigned its own tenant. So metrics for each endpoint will be separate from other endpoints via tenant. The way this is done by a "Tenant" field in the Endpoint YAML config.

However the way this should work is that a pod exposing a metric in project "foo" will write those metrics to tenant "foo". This is how our security setup works with OpenShift. An OpenShift project corresponds to a Hawkular Metrics tenant.

So we need to ensure that all endpoints for all pods in a project are assigned a tenant with the same name as the project.

**Comment by burmanm** [comment]
This can change, as the id that's currently used (it's not the project name) was deprecated in Heapster at least, so it might not be available under that label anymore in the future.

**Comment by jmazzitelli** [comment]
> This can change, as the id that's currently used (it's not the project name) was deprecated in Heapster 

Today, the tenant that is used is NOT the project name? What is the tenant ID based off of?

What we could do is rely on a custom pod annotation - we tell people to annotate the pod with a specific name whose value is the tenant ID to be used for all metrics for that pod.

**Comment by jmazzitelli** [comment]
@burmanm so what is the tenant set to if not the project name? I've got PR #2 that uses the project name (aka namespace) but if that is not right, that PR needs to be rejected and fixed to set the tenant to the proper thing - but I don't know what that proper thing is.

**Comment by mwringe** [comment]
@burmanm what is going on with the project name / namespace changes in Heapster?

**Comment by burmanm** [comment]
This is what's currently used: https://github.com/kubernetes/heapster/blob/master/metrics/core/labels.go#L40 (pod_namespace) and that has been in deprecated stage for some time (commit 0ca19950004c6b07ff83aef76c41d8f276e91e35), almost a year now.

However, given the future of Heapster.. I'm not sure what steps we can take at this moment. In any case, this needs to be a configurable setting.

**Comment by mwringe** [comment]
Ah, "pod_namespace" is deprecated for what I am assuming is just to rename it to "namespace_name".

But this is a Heapster specific label and I don't understand how this would affect the agent?

Also +1 to making this configurable in the agent's configmap so that we can potentially easily modify this in the future.

**Comment by jmazzitelli** [comment]
But we don't want it configurable in the sense that we don't want the pod itself able to define its tenant in its config map, right? That's what the PR got rid of. In the pod's config map, for each endpoint there *was* a Tenant attribute that is configurable - but the PR that was just merged removed that because we don't want the pod to define its own tenant ID. (So right now, in master branch, the endpoint's tenant is being set to the pod's namespace.)

**Comment by mwringe** [comment]
Right, we don't want to have the pods themselves specify the tenant. Otherwise this means that a pod from one project would be able to write metrics to another project (even if it doesn't have access to that project).

What I meant is that we could make this modifiable at the agent level, so we could potentially in the future not use the namespace name as the tenant name but use something else. For now I don't think we need this feature though.

**Comment by jmazzitelli** [comment]
Right now in master branch the tenant for an endpoint is its namespace (aka project) name. If that is how we want it going forward, we can close this issue. Otherwise, we'll need to figure out what the tenant should be.

**Comment by mwringe** [comment]
I think that is good. Lets close this.

**Comment by jmazzitelli** [comment]
sounds good to me! closing.
