### ISSUE TITLE
Allow to use Openshift API data in metric name

### ISSUE THREAD

**Issue by gordillo-ramon-redhat** [hawkular/hawkular-openshift-agent#142]
Some Red Hat Middleware xpaas images expose metrics through jolokia, but the jmx metrics includes pod names, namespaces, etc. For example:

  - name: org.apache.activemq:type=Broker,brokerName=${POD:name}#TotalConnectionsCount
    type: counter
    id:   total_connections_count

We need to include this parameters in name definition.

**Comment by jmazzitelli** [comment]
PR #143 has been submitted and ready for review

**Comment by jmazzitelli** [comment]
PR merged.

**Comment by gordillo-ramon-redhat** [comment]
Although I have previously checked and it seems right, now I have checked with a deploymentconfig that has two pods, and the POD:name that is selecting is the same for both, so it is failing for the second one.

**Comment by jmazzitelli** [comment]
@gordillo-ramon-redhat can you write a separate git issue and provide some replication procedures in the new issue?
