### ISSUE TITLE
HOSA emitter fails to start with master-proxy certs as identity 

### ISSUE THREAD

**Issue by ljuaneda** [hawkular/hawkular-openshift-agent#150]
This is the following of issue https://github.com/hawkular/hawkular-openshift-agent/issues/147

When you set the proper configuration to access a jolokia endpoint from a jbosseap container, you have to add the master-proxy certificates to HOSA identity section.

First, you need to create the **master-proxy secret** in the **default** namespace from master:
```
oc secrets new master-proxy /etc/origin/master/master.proxy-client.crt /etc/origin/master/master.proxy-client.key -n default
```
Add the certificates in the HOSA config file :
```
  config.yaml: |
    kubernetes:
      tenant: ${POD:namespace_name}
    hawkular_server:
      url: https://metrics.osev3-qt9-infra.hpmetier.sf.intra.laposte.fr
      credentials:
        username: secret:openshift-infra/hawkular-metrics-account/hawkular-metrics.username
        password: secret:openshift-infra/hawkular-metrics-account/hawkular-metrics.password
      ca_cert_file: secret:openshift-infra/hawkular-metrics-certificate/hawkular-metrics-ca.certificate
    emitter:
      status_enabled: true
    identity:
      cert_file: /master-proxy/master.proxy-client.crt
      private_key_file: /master-proxy/master.proxy-client.key
    collector:
      minimum_collection_interval: 10s
      default_collection_interval: 30s
      metric_id_prefix: pod/${POD:uid}/custom/
      tags:
        metric_name: ${METRIC:name}
        description: ${METRIC:description}
        units: ${METRIC:units}
        namespace_id: ${POD:namespace_uid}
        namespace_name: ${POD:namespace_name}
        node_name: ${POD:node_name}
        pod_id: ${POD:uid}
        pod_ip: ${POD:ip}
        pod_name: ${POD:name}
        pod_namespace: ${POD:namespace_name}
        hostname: ${POD:hostname}
        host_ip: ${POD:host_ip}
        labels: ${POD:labels}
        type: pod
        collector: hawkular_openshift_agent
        custom_metric: true
```

And then the certificates to the daemonset : 
```
       volumeMounts:
        - mountPath: /master-proxy
          name: master-proxy
...
      volumes:
      - name: master-proxy
        secret:
          defaultMode: 420
          secretName: master-proxy
```
Here, everything is now ok to gather data from jolokia.

But, adding the certs to HOSA has a very bad side effect :
```
I0316 09:25:48.562580       1 discovery.go:172] DEBUG: Changed configmap [hawkular-openshift-agent-configuration] for namespace [default] affects pod [siy05ezb/default/hawkular-openshift-agent-11vyg/cd22f65e-0a28-11e7-9706-0090fae9dd7a] with volume: [hawkular-openshift-agent=hawkular-openshift-agent-configuration]
I0316 09:25:48.562592       1 discovery.go:365] DEBUG: Detected a new configmap [haproxy-config] for namespace [default]
I0316 09:25:48.562667       1 metrics_collector_manager.go:140] START collecting metrics from [default|hawkular-openshift-agent-11vyg|prometheus|http://10.129.5.5:8080/metrics] every [30s]
I0316 09:25:48.562674       1 discovery.go:375] TRACE: Added configmap [haproxy-config] for namespace [default]=ConfigMap[default:haproxy-config]: endpoints:
- type: prometheus
  enabled: "true"
  protocol: http
  port: 9101
  path: /metrics
  tls: {}
  credentials: {}
  collection_interval: 30s
  tags: {}
  metrics: []
I0316 09:25:48.562682       1 discovery.go:175] DEBUG: Changed configmap [haproxy-config] for namespace [default] does not affect pod [siy05ezb/default/hawkular-openshift-agent-11vyg/cd22f65e-0a28-11e7-9706-0090fae9dd7a]
I0316 09:26:18.563499       1 prometheus_metrics_collector.go:97] DEBUG: Told to collect all Prometheus metrics from [http://10.129.5.5:8080/metrics]
W0316 09:26:18.564122       1 metrics_collector_manager.go:181] Failed to collect metrics from [default|hawkular-openshift-agent-11vyg|prometheus|http://10.129.5.5:8080/metrics] at [Thu, 16 Mar 2017 09:26:18 +0000]. err=Failed to collect Prometheus metrics from [http://10.129.5.5:8080/metrics]. err=Cannot scrape Prometheus URL [http://10.129.5.5:8080/metrics]: err=Get http://10.129.5.5:8080/metrics: dial tcp 10.129.5.5:8080: getsockopt: connection refused
```
... leading all the HOSA pods to fail :
```
[root@siy05ez1:~]# oc get pods -l metrics-infra=agent
NAME                             READY     STATUS             RESTARTS   AGE
hawkular-openshift-agent-11vyg   0/1       CrashLoopBackOff   7          15m
hawkular-openshift-agent-67dhv   0/1       CrashLoopBackOff   7          15m
hawkular-openshift-agent-68km4   0/1       CrashLoopBackOff   7          15m
hawkular-openshift-agent-82qac   0/1       CrashLoopBackOff   7          15m
hawkular-openshift-agent-95zht   0/1       CrashLoopBackOff   7          15m
hawkular-openshift-agent-a479w   0/1       CrashLoopBackOff   7          15m
hawkular-openshift-agent-au8os   0/1       CrashLoopBackOff   7          15m
hawkular-openshift-agent-k4y5r   0/1       CrashLoopBackOff   7          15m
hawkular-openshift-agent-tyh2m   0/1       CrashLoopBackOff   7          15m
hawkular-openshift-agent-xph04   0/1       CrashLoopBackOff   7          15m
```

> https://github.com/hawkular/hawkular-openshift-agent/issues/147#issuecomment-287176266

All this could be fix with https://github.com/hawkular/hawkular-openshift-agent/issues/75

Meanwhile, I had to disable the liveness probe in HOSA daemonset configuration.

**Comment by jmazzitelli** [comment]
I'm going to temporarily turn off the ability for the emitter to be configured behind https protocol. If you do not want status or metrics or health endpoints behind http, you can disable them. But for now, even if you give the agent its identity, it doesn't matter - the emitter endpoints (status, metrics, health) are going to be behind http only. Thus no need to disable the liveness probe and the /metrics endpoint should work.

**Comment by jmazzitelli** [comment]
OK, that PR is merged. Use the "latest" on docker hub to pick up this change.

Note that if you do not want the emitter to be behind http, you can disable them in the emitter config section of the agent configuration. If you keep them enabled, you can still secure the metrics and status endpoints with credentials:

```
emitter:
   metrics_credentials:
      username: foo1
      password: bar1
   status_credentials:
      username: foo2
      password: bar2
```

This means anyone attempting to talk to the /status and /metrics endpoints need to supply those name/password credentials to gain access. This is true even if going over http.

**Comment by ljuaneda** [comment]
Tested this morning.
Seems ok so far

**Comment by gordillo-ramon-redhat** [comment]
The original problem was related because if you configured cert for the agent, automatically the emitter changed to be on 8443, so the health livenessprobe in the template should be changed accordingly. With that, OCP will check it correctly, and you don't need this patch.

**Comment by jmazzitelli** [comment]
@gordillo-ramon-redhat so what you are saying is that if you give the agent an identity, your health liveness probe needs to refer to port 8443. 

I think I should remove this patch - that should always have been the case (I guess I just didn't document it). If you give the agent an identity, that will switch the emitter endpoint to use https and if you did not declare an "address" in the "emitter" configuration section, it switches to port 8443 in that case.

So that means the /health endpoint is also on that port on https and any liveness probes need to be configured accordingly.

This is mentioned in the README - but its not obvious. It is in the environment variable documentation for EMITTER_ADDRESS variable:

https://github.com/hawkular/hawkular-openshift-agent/blob/master/README.adoc#environment-variables

```
If the emitter endpoint is to be enabled, this is the bind address and port.
If address is not specified, it will be an IP of the host machine. If not specified at all,
this will be either ":8080" if the agent’s identity is not declared and ":8443" if the
agent’s identity is declared. Note that if the agent’s identity is declared, the
endpoint will be exposed over https, otherwise http is used. If neither metrics, status,
or health emitters are enabled, this setting is not used and no http(s) endpoint
is created by the agent.

emitter:
  address: [address]:port
```

**Comment by jmazzitelli** [comment]
PR #160 reverts the previous change - go back to enabling https (and using default port 8443 if emitter:address isn't specified)

**Comment by jmazzitelli** [comment]
PR #160 merged - reverts to original behavior. Change the liveness probe if you require the agent emitter to be accessed over https (which is implied when you provide the agent with an identity)
