### ISSUE TITLE
HOSA fails for parse Jolokia Response returned by Fuse Integration Service image

### ISSUE THREAD

**Issue by lbroudoux** [hawkular/hawkular-openshift-agent#174]
Hi, 

I'm trying to setup HOSA on an OpenShift v3.6.0 installation (actually my laptop using Minishift 1.4.1). I have a demonstration application built using Fuse Integration Services 2.0 (Red Hat official images [here](https://access.redhat.com/documentation/en-us/red_hat_jboss_fuse/6.3/html-single/fuse_integration_services_2.0_for_openshift)).

I've done the setup following this [blog post](http://www.hawkular.org/blog/2017/01/17/obst-hosa.html) and the OpenShift [documentation](https://docs.openshift.com/container-platform/3.6/install_config/cluster_metrics.html#deploying-hawkular-openshift-agent). 

Connection to the Jolokia agent of my FIS application is OK but agent complains filing parsing Jolokia response: 

````
W0822 15:34:27.589351       1 metrics_collector_manager.go:181] Failed to collect metrics from [techlab-demo-2|api-gateway-7-ppnxx|jolokia|https://172.17.0.17:8778/jolokia/] at [Tue, 22 Aug 2017 15:34:27 +0000]. err=Failed to collect metrics from Jolokia endpoint [https://172.17.0.17:8778/jolokia/]. err=Failed to parse Jolokia response. err=json: cannot unmarshal object into Go value of type []jolokia.JolokiaResponse
````

The agent used is Hawkular OpenShift Agent: Version: 1.2.2.Final and the Docker image used is openshift3/metrics-hawkular-openshift-agent:v3.6. It seems there's new docker images available for HOSA [here](https://hub.docker.com/r/hawkular/hawkular-openshift-agent/tags/) but they do not seems to be releases within OpenShift.

Any hint on what's going wrong ?

Thanks,

**Comment by jmazzitelli** [comment]
You are using an obsolete version of HOSA. The latest release is 1.4.1.Final as you see here on HOSA's docker hub: https://hub.docker.com/r/hawkular/hawkular-openshift-agent/tags/

Use that version of HOSA and I believe your problem will go away.

**Comment by lbroudoux** [comment]
You're right : I've updated the image definition to hawkular/hawkular-openshift-agent:1.4.1.Final and it works ! I believe the OpenShift versions were the most stable one but they're obsolete.

Many thanks,
