### ISSUE TITLE
Project Structure

### ISSUE THREAD

**Issue by mwringe** [hawkular/hawkular-openshift-agent#24]
Is there any reason why the project does not follow golang conventions?

The current setup where the root of the project is the GOPATH is quite strange.

If this is not a glide convention, can we please reconfigure the structure to properly match what is expected of a golang based project?

**Comment by jmazzitelli** [comment]
I thought it made it easier for people to install.  Otherwise, you have you to create your own GOPATH structure and then git clone into src. Is that typically how people do it even for non-library golang projects like this one?

**Comment by jmazzitelli** [comment]
OK, I see it: https://github.com/golang/go/wiki/GithubCodeLayout

I'll rearrange it following those recommendations.

**Comment by mwringe** [comment]
Cool, I moved it around locally to be more like a normal project, its not that difficult to make the change

**Comment by jmazzitelli** [comment]
This is done. Pull master and you'll get your new project structure as recommended by https://github.com/golang/go/wiki/GithubCodeLayout
