### ISSUE TITLE
define default tags

### ISSUE THREAD

**Issue by jmazzitelli** [hawkular/hawkular-openshift-agent#33]
Rather than require someone to enter tags that we most likely want them to use when deployed in OpenShift, let's create a default set of tags if the user didn't define any.

For example, if the global config yaml doesn't have any tags defined, we should default to this list or something like it:

tags:
  namespace_id: ${POD:namespace_uid}
  namespace_name: ${POD:namespace_name}
  node_name: ${POD:node_name}
  pod_id: ${POD:uid}
  pod_name: ${POD:name}
  pod_namespace: ${POD:namespace_name}
  hostname: ${POD:hostname}
  subdomain: ${POD:subdomain}
  labels: ${POD:labels}

Note that if the agent is not deployed in OpenShift, we should provide a different default list (or just leave the list empty). We know if its deployed in OpenShift by the mere fact that the K8S_POD_NAMESPACE (or kubernetes: pod_namespace: yaml setting) is defined. If that config setting is defined and not empty, and no tags are set, we should provide the above default set of tags (maybe we always use these tags - if the user define their own, we just add the above to their custom list)?

**Comment by mwringe** [comment]
I think we have this now and it can be closed, right?

On OpenShift we are using these global tags: https://github.com/hawkular/hawkular-openshift-agent/blob/master/deploy/openshift/hawkular-openshift-agent-configmap.yaml#L15

**Comment by jmazzitelli** [comment]
Yeah, this can be closed I think. I think we got it the way we want it.
