### ISSUE TITLE
Prometheus Endpoints shouldn't need to specify its type

### ISSUE THREAD

**Issue by mwringe** [hawkular/hawkular-openshift-agent#53]
Prometheus endpoints can specify what its type is, if not explicit type is specified, then we should just gather this type from the endpoint directly.

eg, from the python example:

> \# TYPE process_virtual_memory_bytes **gauge**

**Comment by jmazzitelli** [comment]
this is fixed by PR #55

**Comment by jmazzitelli** [comment]
you no longer need to specify the metric type (gauge/counter) for Prometheus metrics.
