### ISSUE TITLE
Include the prometheus help doctext as a tag

### ISSUE THREAD

**Issue by mwringe** [hawkular/hawkular-openshift-agent#54]
If we are reading from a prometheus endpoint and that metric has a help line which provides some doctext, we should be including that text as a label in the pod definition.

**Comment by jmazzitelli** [comment]
PR #60 does this now. We now make have an API to the collector interface to ask for metric details such as metric type and description. This allows our Prometheus implementation to obtain this and we use it to place in metric descriptions.

**Comment by jmazzitelli** [comment]
this is done via PR #60
