### ISSUE TITLE
Push Example images to docker hub

### ISSUE THREAD

**Issue by mwringe** [hawkular/hawkular-openshift-agent#66]
To make things easier for users, we should probably push out example docker images to docker hub. This will allow them to deploy the examples without having to build the images directly.

**Comment by jmazzitelli** [comment]
Right now they are on docker hub but in our personal hubs (the jolokia one is in mine at https://hub.docker.com/r/jmazzitelli/jolokia-wildfly/ and the prometheus one is in @mwringe 's hub at https://hub.docker.com/r/mwringe/example-prometheus/

We should put these in hawkular's hub under: https://hub.docker.com/u/hawkular/

**Comment by jmazzitelli** [comment]
I'll do this as part of the work for issue #68 - maybe we can push the examples automatically from travis too?

**Comment by mwringe** [comment]
Yeah, for any images we have (agent, examples, etc) they should be pushed to github with the 'latest' tag when the travis build completes.

**Comment by jmazzitelli** [comment]
This is done via PR #83 and commit 52b6a69bfd70f9d651f81f3e71a28ec3ad23d7ac

The docker images will be tagged with "latest" as you see here:

* https://hub.docker.com/r/hawkular/hawkular-openshift-agent/tags/
* https://hub.docker.com/r/hawkular/hawkular-openshift-agent-example-prometheus-python/tags/
* https://hub.docker.com/r/hawkular/hawkular-openshift-agent-example-jolokia-wildfly/tags/
