### ISSUE TITLE
Automatically Push Docker Images on Merge

### ISSUE THREAD

**Issue by mwringe** [hawkular/hawkular-openshift-agent#68]
We should update our CI to automatically push docker images on merge.

**Comment by jmazzitelli** [comment]
somewhat related, see issue #66 where we want to also push the examples to hawkular's docker hub

**Comment by jmazzitelli** [comment]
I'm going to look into doing this - travis has a way to publish things to docker hub. Just have to read up on how they support this.

**Comment by jmazzitelli** [comment]
This is done via PR #83 and commit 52b6a69bfd70f9d651f81f3e71a28ec3ad23d7ac

The docker images will be tagged with "latest" as you see here:

* https://hub.docker.com/r/hawkular/hawkular-openshift-agent/tags/
* https://hub.docker.com/r/hawkular/hawkular-openshift-agent-example-prometheus-python/tags/
* https://hub.docker.com/r/hawkular/hawkular-openshift-agent-example-jolokia-wildfly/tags/
