### ISSUE TITLE
Configure the intervals using Go lang duration values rather than seconds.

### ISSUE THREAD

**Issue by mwringe** [hawkular/hawkular-openshift-agent#93]
Instead of using a parameter named `collection_interval_secs` we should just have a parameter called `collection_interval` which takes a string representation of a Go time value.

eg:
`collection_interval: 10s`
`collection_interval: 1m`
`collection_interval: 5m`

**Comment by jmazzitelli** [comment]
see PR #95 - seems to work nicely.
